services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOCKERIZED=true
      - HOST=db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: maslova
      POSTGRES_PASSWORD: maslova_pw
      POSTGRES_DB: pizza_service_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
